language: ruby
cache: bundler
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site --trace
deploy:
  provider: pages
  local-dir: ./site
  target-branch: gh-pages
  email: ala1289@gmail.com
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
